### PR TITLE
chore(user): [SFEQS-1138] Minor fix openapi

### PR DESCRIPTION
**Pull request by grausof**
Minor fix to openapi

### CODE REVIEW

**Review by gunzip — APPROVED** [review]
can you link the jira issue?

**Comment by lucacavallaro** [comment]
> can you link the jira issue?

Is the JIRA issue needed for this kind of changes? we can use this PR as reference

**Comment by grausof** [comment]
> can you link the jira issue?

Yes, this is a minor fix to #35 
I have however updated the title with the main jira id

**Comment by gunzip** [comment]
@lucacavallaro  what do you mean with "we can use this PR as reference"? we have a "contract" in swarmia set up that count unlinked PRs. If we want to have unlinked PR I'd rather switch off this control.

**Comment by lucacavallaro** [comment]
> @lucacavallaro what do you mean with "we can use this PR as reference"? we have a "contract" in swarmia set up that count unlinked PRs. If we want to have unlinked PR I'd rather switch off this control.

No ok, you are right. We can keep the contract!

**Pull request merged**
